name: plant-seg
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - h5py
  - zarr
  - requests
  - pyyaml
  - scikit-image
  - tifffile
  - vigra
  - pytorch
  - python-elf
  - napari
  - python-graphviz