name: plantseg-seg-dev
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  # Neural Network and GPU
  - conda-forge::cudnn=9
  - pytorch=2.4
  - torchvision
  - pytorch-cuda=12.1
  - cuda-version>=12.1
  # Bioimage and CV
  - tifffile
  - h5py
  - zarr
  - vigra
  - python-elf
  - python-graphviz
  - scikit-image
  - bioimageio.core>=0.6.5
  # GUI
  - pyqt
  - napari
  # Other
  - requests
  - pyyaml
  - pydantic>2
  - pytest
  - pytest-qt
  # CI/CD
  - pre-commit
  - bump-my-version
  # Docs
  - mkdocs-material
  - mkdocs-autorefs
  - mkdocs-git-revision-date-localized-plugin
  - mkdocs-git-committers-plugin-2
  - mkdocstrings-python
  - pip:
      - markdown-exec
      # PlantSeg
      - -e .
