name: plant-seg
channels:
  - awolny
  - lcerrone
  - pytorch
  - conda-forge
dependencies:
  - python =3.9
  - h5py
  - requests
  - pyyaml
  - scikit-image
  - tifffile
  - vigra
  - pytorch
  - python-elf
  - pytorch-3dunet =>1.3.7
