[tool.typos.default.extend-words]
nd = "nd"       # N-dimensional (ND)
ome = "ome"     # Open Microscopy Environment (OME)
datas = "datas" # pyinstaller

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.format]
quote-style = "preserve"

[tool.bumpversion]
current_version = "2.0.0-alpha"
parse = """(?x)
    (?P<major>[0-9]+)
    \\.(?P<minor>[0-9]+)
    \\.(?P<patch>[0-9]+)
    (?:
        -(?P<pre_label>alpha|beta|stable)
        (?:.(?P<pre_n>[0-9]+))?
    )?
"""
serialize = [
    "{major}.{minor}.{patch}-{pre_label}.{pre_n}",
    "{major}.{minor}.{patch}",
]
search = "{current_version}"
replace = "{new_version}"
tag = true
commit = true
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
message = "Bump version: {current_version} → {new_version}"
commit_args = "--no-verify"

[tool.bumpversion.parts.pre_label]
optional_value = "stable"
values = ["alpha", "beta", "stable"]

[[tool.bumpversion.files]]
filename = "plantseg/__version__.py"
