[tool.typos.default.extend-words]
nd = "nd"       # N-dimensional (ND)
ome = "ome"     # Open Microscopy Environment (OME)
datas = "datas" # pyinstaller

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.format]
quote-style = "preserve"

[tool.bumpversion]
current_version = "2.0.0a0"
parse = """(?x)
    (?P<major>[0-9]+)               # Major version
    \\.(?P<minor>[0-9]+)            # Minor version
    \\.(?P<patch>[0-9]+)            # Patch version
    (?:
        (?P<pre_label>a|b|rc)       # Pre-release label (alpha, beta, release candidate)
        (?P<pre_n>[0-9]+)           # Pre-release number (0, 1, 2, etc.)
    )?
"""
serialize = [
    "{major}.{minor}.{patch}{pre_label}{pre_n}", # Pre-release format: 2.0.0a0
    "{major}.{minor}.{patch}",                   # Stable version format: 2.0.0
]
search = "{current_version}"
replace = "{new_version}"
tag = true
commit = true
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
message = "Bump version: {current_version} → {new_version}"
commit_args = "--no-verify"

[tool.bumpversion.parts.pre_label]
optional_value = "stable"
values = ["a", "b", "rc", "stable"]

[[tool.bumpversion.files]]
filename = "plantseg/__version__.py"
