package:
  name: plantseg
  version: {{ RELEASE_VERSION }}  # Do not change this line, not even adding space

source:
  path: ..

build:
  noarch: python
  script: "pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  number: 1

  entry_points:
    - plantseg = plantseg.run_plantseg:main

requirements:
  build:
    - python
    - pip

  run:
    - python
    - pytorch
    - tifffile
    - h5py
    - zarr
    - vigra
    - python-elf
    - python-graphviz
    - scikit-image
    - bioimageio.core>=0.6.5
    - napari
    - requests
    - pyyaml
    - pydantic>2

test:
  imports:
    - plantseg
  requires:
    - pytest
  run:
    - pytest
about:
  home: https://kreshuklab.github.io/plant-seg/
  license: MIT
